version: "3.9"
services:
  redis:
    image: redis:alpine
    restart: always

  hitcounter:
    depends_on:
      - redis
    build: .
    restart: always
    ports:
      - "9080:8080"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"